---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: goserver
  namespace: goserver
spec:
  interval: 2m0s
  ref:
    branch: madhu-changes
  secretRef:
    name: idpops-github-creds
  timeout: 300s
  url: https://github.com/idppoc/idpops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: goserver
  namespace: goserver
spec:
  interval: 3m0s
  path: ./products/aws/aws-account-1/us-west-2/ipdops-cluser/goserver
  prune: true
  sourceRef:
    kind: GitRepository
    name: goserver
  validation: client
