apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goserver
  namespace: goserver
spec:
  chart:
    spec:
      chart: goserver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: goserver
      version: 0.1.1
  interval: 15m0s
  releaseName: goserver
  values:
    replicaCount: 1
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
