---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 2m0s
  ref:
    branch: main
  secretRef:
    name: idpops-github-creds
  timeout: 300s
  url: https://github.com/idppoc/idpops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 3m0s
  path: ./products/aws/aws-account-1/us-west-2/product1-cluster/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
