---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app1
  namespace: app1
spec:
  interval: 15m0s
  ref:
    branch: master
  secretRef:
    name: idpops-github-creds
  timeout: 300s
  url: https://github.com/idppoc/idpops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1
  namespace: app1
spec:
  interval: 3m0s
  path: ./products/aws/aws-account-1/us-west-2/product-java-app/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
