apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.helm.sh/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-charts
  namespace: flux-system
spec:
  interval: 4h
  url: https://helm.nginx.com/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-dashboard
  namespace: flux-system
spec:
  interval: 4h
  url: https://kubernetes.github.io/dashboard/
---


