---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: idp-webapp
  namespace: idp-webapp
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: idpops-github-creds
  timeout: 300s
  url: https://github.com/idppoc/idpops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: idp-webapp
  namespace: idp-webapp
spec:
  interval: 1m0s
  path: ./products/aws/aws-account-1/us-west-2/product2-ui-cluster/idp-webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: idp-webapp
  validation: client
